### ISSUE TITLE
I can't see any data after installation

### ISSUE THREAD

**Issue by joelramone** [unifi-poller/unifi-poller#288] opened 2020-12-21 19:34 UTC
Hi!
After installing unifi-poller aver docker-compose, I can't see any data on grafana dashboard. 
How can I see errors or logs to figure the problem out?
Thank you!

**Comment by davidnewhall** [comment] 2020-12-21 20:17
How to look at logs for a Docker app:
```
docker logs <container id>
```

How to get the container ID:
```
docker ps
```

If you need help troubleshooting, please provide your Influx, Grafana and Poller versions. 90% of the time "not data" is caused by "old influx" - make sure you're on at least 1.7.x.

**Comment by joelramone** [comment] 2020-12-22 13:21
Hi, thank ou for your Answer @davidnewhall, now I see the next log:

 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
 [INFO] Loading Configuration File: /config/unifi-poller.conf
 [INFO] UniFi Poller v2.0.1-787 Starting Up! PID: 1
 [INFO] Found 1 site(s) on controller https://192.168.21.109:8443: default (Default)
 [INFO] Configured UniFi Controller 1:
 [INFO]    => URL: https://192.168.21.109:8443
 [INFO]    => Version: 6.0.36
 [INFO]    => Username: unifipoller (has password: true)
 [INFO]    => Hash PII: false
 [INFO]    => Verify SSL: false
 [INFO]    => Save DPI: true
 [INFO]    => Save IDS: false
 [INFO]    => Save Sites: true
 
 I don't get what I'm doing wrong, I'd already config te influxDB, both docker.yml and up.conf
 Thank you in advance

**Comment by davidnewhall** [comment] 2020-12-22 20:50
I don't know what you're doing wrong either. Show me the problem, and provide the information requested in my previous comment please.

**Comment by joelramone** [comment] 2020-12-23 14:08
Hi David
I have this currently versions:
Graffana: 7.3.5
Influxdb: 1.8.3
Poller: 1.8

**Comment by davidnewhall** [comment] 2020-12-23 19:17
Can you attach some screenshots or something? I do not know what your problem is. You haven't told me what you did to get to where you are, only that it's not working.

**Comment by joelramone** [comment] 2020-12-28 12:30
Hi @davidnewhall here are my config files:
**docker-compose.ymal**
`version: "3"
services:
  influxdb:
    container_name: up_influxdb
    restart: unless-stopped
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - /home/free/Docker/unipoller/unifi-poller/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=unifi
      - INFLUXDB_ADMIN_USER=unifipoller
      - INFLUXDB_ADMIN_PASSWORD=unifipoller

  grafana:
    container_name: up_grafana
    image: grafana/grafana
    restart: unless-stopped
    #user: 1000:1000
    ports:
      - '3000:3000'
    volumes:
      - /home/free/Docker/unipoller/unifi-poller/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel

  unifi-poller:
    container_name: up-poller
    restart: unless-stopped
    image: golift/unifi-poller:latest
    depends_on:
      - influxdb
      - grafana
    volumes:
      - /home/free/Docker/unipoller/unifi-poller:/config

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
`
**unifi-poller.conf**
`[unifi.defaults]
  url        = "https://192.168.21.109:8443"
  user       = "unifipoller"
  pass       = "secundop150"
  sites      = ["10.100.5.230"]
  save_ids   = false
  save_dpi   = false
  save_sites = true
  hash_pii   = false
  verify_ssl = false
[influxdb]
  url  = "http://172.21.46.103:8086"
`

**up.conf**
`# UniFi Poller v2 primary configuration file. TOML FORMAT #
###########################################################

[poller]
  # Turns on line numbers, microsecond logging, and a per-device log.
  # The default is false, but I personally leave this on at home (four devices).
  # This may be noisy if you have a lot of devices. It adds one line per device.
  debug = false

  # Turns off per-interval logs. Only startup and error logs will be emitted.
  # Recommend enabling debug with this setting for better error logging.
  quiet = false

  # Load dynamic plugins. Advanced use; only sample mysql plugin provided by default.
  plugins = []

#### OUTPUTS

    # If you don't use an output, you can disable it.

[prometheus]
  disable = false
  # This controls on which ip and port /metrics is exported when mode is "prometheus".
  # This has no effect in other modes. Must contain a colon and port.
  http_listen = "0.0.0.0:9130"
  report_errors = false

[influxdb]
  disable = false
  # InfluxDB does not require auth by default, so the user/password are probably unimportant.
  url  = "http://172.21.46.103:8086"
  user = "unifipoller"
  pass = "unifipoller"
  # Be sure to create this database.
  db = "unifi"
  # If your InfluxDB uses a valid SSL cert, set this to true.
  verify_ssl = false
  # The UniFi Controller only updates traffic stats about every 30 seconds.
  # Setting this to something lower may lead to "zeros" in your data.
  # If you're getting zeros now, set this to "1m"
  interval = "30s"

#### INPUTS

[unifi]
  # Setting this to true and providing default credentials allows you to skip
  # configuring controllers in this config file. Instead you configure them in
  # your prometheus.yml config. Prometheus then sends the controller URL to
  # unifi-poller when it performs the scrape. This is useful if you have many,
  # or changing controllers. Most people can leave this off. See wiki for more.
  dynamic = false

# The following section contains the default credentials/configuration for any
# dynamic controller (see above section), or the primary controller if you do not
# provide one and dynamic is disabled. In other words, you can just add your
# controller here and delete the following section. The internal defaults are
# shown below. Any missing values will assume these displayed defaults.
[unifi.defaults]
  url        = "https://192.168.21.109:8443"
  user       = "unifipoller"
  pass       = "secundop150"
  sites      = ["10.100.5.230"]
  save_ids   = false
  save_dpi   = false
  save_sites = true
  hash_pii   = false
  verify_ssl = false

# The following is optional and used for configurations with multiple controllers.

# You may repeat the following section to poll multiple controllers.
# Any ommitted variables will have their values taken from the defaults, above.
#[[unifi.controller]]
  # URL for the UniFi Controller. Do not add any paths after the host:port.
  # Do not use port 8443 if you have a UDM.
  #url = "https://192.168.21.109:8443"

  # Make a read-only user in the UniFi Admin Settings, allow it access to all sites.
  #user = "unifipoller"
  #pass = "secundop150"

  # If the controller has more than one site, specify which sites to poll here.
  # Set this to ["default"] to poll only the first site on the controller.
  # A setting of ["all"] will poll all sites; this works if you only have 1 site too.
  #sites = ["all"]

  # Enable collection of Intrusion Detection System Data (InfluxDB only).
  # Only useful if IDS or IPS are enabled on one of the sites.
  #save_ids = false

  # Enable collection of Deep Packet Inspection data. This data breaks down traffic
  # types for each client and site, it powers a dedicated DPI dashboard.
  # Enabling this adds roughly 150 data points per client.  That's 6000 metrics for
  # 40 clients.  This adds a little bit of poller run time per interval and causes
  # more API requests to your controller(s). Don't let these "cons" sway you:
  # it's cool data. Please provide feedback on your experience with this feature.
  #save_dpi = false

  # Enable collection of site data. This data powers the Network Sites dashboard.
  # It's not valuable to everyone and setting this to false will save resources.
  #save_sites = true

  # Hash, with md5, client names and MAC addresses. This attempts to protect
  # personally identifiable information. Most users won't want to enable this.
  #hash_pii = false

  # If your UniFi controller has a valid SSL certificate (like lets encrypt),
  # you can enable this option to validate it. Otherwise, any SSL certificate is
  # valid. If you don't know if you have a valid SSL cert, then you don't have one.
  #verify_ssl = false
`
If you can see any error, please let me know. 
Thank you

**Comment by davidnewhall** [comment] 2020-12-28 12:32
Check your Grafana data source, and re-import the dashboards Then attach a screenshot of the problem.

**Comment by joelramone** [comment] 2020-12-28 12:45
@davidnewhall 
Here is a screenshot 
![grafanaprintscreen](https://user-images.githubusercontent.com/15172210/103215193-68f2e880-48f1-11eb-8eee-155e672d11bf.png)

**Comment by davidnewhall** [comment] 2020-12-28 20:56
> As you can see just one site is detected an no AP are displayed.

You clearly limited sites in your config.  `sites      = ["10.100.5.230"]`
It doesn't even make sense. Why did you put an IP there?

**Comment by joelramone** [comment] 2020-12-29 15:04
Yeah, that's because I've been testing, but we can have the same result with "all" parameter.

**Comment by davidnewhall** [comment] 2020-12-29 20:07
> [INFO] Found 1 site(s) on controller https://192.168.21.109:8443: default (Default)

Make sure the `unifipoller` user has access to all your sites.

**Comment by davidnewhall** [comment] 2021-01-11 20:01
Were you able to figure this out?

**Comment by JoshFrawley** [comment] 2021-01-19 21:00
Hello, 

I am having a similar issue. When I start I can see that everything seems to be working 
`
up-poller       | 2021/01/19 20:48:08 [INFO] Configured UniFi Controller 1:
up-poller       | 2021/01/19 20:48:08 [INFO]    => URL: https://10.10.0.10:8443
up-poller       | 2021/01/19 20:48:08 [INFO]    => Version: 6.0.41
up-poller       | 2021/01/19 20:48:08 [INFO]    => Username: Poll (has password: true)
up-poller       | 2021/01/19 20:48:08 [INFO]    => Hash PII: false
up-poller       | 2021/01/19 20:48:08 [INFO]    => Verify SSL: false
up-poller       | 2021/01/19 20:48:08 [INFO]    => Save DPI: true
up-poller       | 2021/01/19 20:48:08 [INFO]    => Save IDS: false
up-poller       | 2021/01/19 20:48:08 [INFO]    => Save Sites: true
up-poller       | 2021/01/19 20:48:08 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
`
After this is will detect all my sites and give me more information. 

When I look whats going on the VM when loading graphs in grafana it will show me the requests being sent. 
`up_influxdb     | [httpd] 10.10.0.48, 10.10.0.48,172.20.0.1 - unifi [19/Jan/2021:20:42:38 +0000] "GET /query?db=unifi&epoch=ms&q=SELECT+non_negative_derivative%28sum%28%22rx_bytes%22%29%2C+1s%29+AS+%22Bytes+Rx%22%2C+non_negative_derivative%28sum%28%22tx_bytes%22%29%2C+1s%29+AS+%22Bytes+Tx%22+FROM+%22sitedpi%22+WHERE+%28%22site_name%22+%3D~+%2F%5EHome+%5C%28default%5C%29%24%2F%29+AND+time+%3E%3D+now%28%29+-+3h+and+time+%3C%3D+now%28%29+-+5s+GROUP+BY+time%2810s%29%2C+%22category%22 HTTP/1.1" 200 57 "-" "Grafana/7.3.7" de3f5c77-5a96-11eb-80a7-0242ac140002 120481
`
Then I get 
`
up-poller       | 2021/01/19 20:55:46 [ERROR] influxdb.Write(points): {"error":"Request Entity Too Large"}
up_influxdb     | [httpd] 172.20.0.1 - unifipoller [19/Jan/2021:20:55:45 +0000] "POST /write?consistency=&db=unifi&precision=ns&rp= HTTP/1.1" 413 37 "-" "InfluxDBClient" b32b06cc-5a98-11eb-8001-0242ac140002 667491
`


when I look In the logs I can see the same error

``
2021/01/19 20:51:04 [INFO] Configured UniFi Controller 1:
2021/01/19 20:51:04 [INFO]    => URL: https://10.10.0.10:8443
2021/01/19 20:51:04 [INFO]    => Version: 6.0.41
2021/01/19 20:51:04 [INFO]    => Username: Poll (has password: true)
2021/01/19 20:51:04 [INFO]    => Hash PII: false
2021/01/19 20:51:04 [INFO]    => Verify SSL: false
2021/01/19 20:51:04 [INFO]    => Save DPI: true
2021/01/19 20:51:04 [INFO]    => Save IDS: false
2021/01/19 20:51:04 [INFO]    => Save Sites: true
2021/01/19 20:51:04 [INFO] Prometheus exported at https://0.0.0.0:9130/ - namespace: unifipoller
2021/01/19 20:51:04 [INFO] Everything checks out! Poller started, InfluxDB interval: 30s
2021/01/19 20:55:46 [ERROR] influxdb.Write(points): {"error":"Request Entity Too Large"}
``

**Comment by davidnewhall** [comment] 2021-01-19 21:09
What version of InfluxDB?

**Comment by JoshFrawley** [comment] 2021-01-19 21:14
> InfluxDB
hi David


HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 3f3cf599-5a9b-11eb-8032-0242ac140002
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.3
X-Request-Id: 3f3cf599-5a9b-11eb-8032-0242ac140002

**Comment by davidnewhall** [comment] 2021-01-19 21:15
Roughly, how many sites, devices and clients do you have?

**Comment by JoshFrawley** [comment] 2021-01-19 21:15
52

**Comment by davidnewhall** [comment] 2021-01-19 21:18
52 sites?
Try increasing influxdb `max-body-size`:
https://docs.influxdata.com/influxdb/v1.8/administration/config/#max-body-size-25000000

Recommend doubling it. Your influxdb is about to grow to a ridiculous size too, just FYI. I'd guess you'll top 100GB/week.

**Comment by JoshFrawley** [comment] 2021-01-19 21:30
i'm running the application in docker and can't find the conf file. Do you know here It is stored?

**Comment by davidnewhall** [comment] 2021-01-19 21:30
use an env variable like Docker does.
`INFLUXDB_HTTP_MAX_BODY_SIZE=50000000`

**Comment by JoshFrawley** [comment] 2021-01-21 15:32
hello, 

I have tried this with both -v and creating the config file and editing it and I'm getting the same issues. I can see the request being generated then saying HTTP errors

**Comment by davidnewhall** [comment] 2021-01-23 17:09
Try collecting data from only a few sites instead of all 52. `Request Entity Too Large` is an InfluxDB error message. The fix is to decrease the amount of data being written (fewer sites/devices/clients), or to increase the max body size as described above. I have no other tricks for this. You're the first (and presumably only) person to report this issue. I have 1 site, 5 devices and 50 clients, so I cannot reproduce this.

**Comment by davidnewhall** [comment] 2021-03-08 02:37
Closing as not much I can do here atm. If you want to work on data reduction for your environment, please hop on Discord and @ me so we can chat about it. Thanks!

**Closed by davidnewhall** 2021-03-08 02:37 UTC
